services:
  fivemfrance-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fivem-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Europe/Paris
